name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    name: tests (macos-14 / py3.13)
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - uses: astral-sh/setup-uv@v2
      - name: Install package
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -e .
      - name: Run tests
        run: |
          uv run pytest -q
